apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-p1gx
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ghko-tenant/status-quarkus-io/statusquarkusio-p1gx@sha256:802c907618a12eb6f561f193fc66c6912e5115bcbb43340adf809c2051fdfe78
        name: my-java-quarkus
        resources: {}
status: {}
